apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: demo-cluster
  region: eu-central-1

nodeGroups:
  - name: ng-demo-1
    instanceType: t3.micro
    desiredCapacity: 3
    minSize: 1
    maxSize: 4
